# Generated by Django 3.0.1 on 2019-12-21 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DA', '아빠'), ('MO', '엄마'), ('1S', '첫째'), ('2S', '둘째'), ('3S', '셋째')], max_length=2)),
                ('phone_number', models.CharField(max_length=11)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.Family')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
