# Generated by Django 3.0.1 on 2019-12-21 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
        ('custom_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='family.Family'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('DA', '아빠'), ('MO', '엄마'), ('1S', '첫째'), ('2S', '둘째'), ('3S', '셋째')], max_length=2, null=True),
        ),
    ]
