# Generated by Django 3.0.1 on 2019-12-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0002_auto_20191221_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='family',
        ),
        migrations.AddField(
            model_name='account',
            name='family_id',
            field=models.IntegerField(default=-1),
        ),
    ]
