# Generated by Django 3.0.1 on 2019-12-21 16:49

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0003_auto_20191221_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='', upload_to='media/%Y-%m-%d/'),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='notifications',
            field=models.TextField(default='[]'),
        ),
    ]
