# Generated by Django 3.0.1 on 2019-12-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0003_auto_20191221_2358'),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Family',
        ),
    ]
